version: '3.9'

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
    volumes:
      - ./data:/app/data
